name: Enable Auto-Merge for Dependabot PRs

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - labeled

jobs:
  enable-auto-merge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
