version: 2

updates:
  # 🔧 JS пакети (npm, yarn)
  - package-ecosystem: "npm"
    directory: "/" # шлях до package.json
    schedule:
      interval: "weekly"
      time: "22:00"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    commit-message:
      prefix: "build(npm)"
    allow:
      - dependency-type: "direct"

  # 🧩 PHP пакети (Laravel / Composer)
  - package-ecosystem: "composer"
    directory: "/" # шлях до composer.json
    schedule:
      interval: "daily"
      time: "23:30"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    commit-message:
      prefix: "build(composer)"
    allow:
      - dependency-type: "direct"

  # 🤖 GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/" # шлях до .github/workflows
    schedule:
      interval: "monthly"
      time: "00:30"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    commit-message:
      prefix: "chore(actions)"
