<?php

return [
    'guides' => [
        'getting-started' => ['title' => 'Getting started', 'description' => 'Install Lazy UI 2.x on Laravel 12 or 13 with Tailwind CSS 4 and daisyUI 5.'],
        'upgrade' => ['title' => 'Upgrade from 1.x', 'description' => 'Migration checklist for Lazy UI 1.x applications.'],
        'themes' => ['title' => 'Themes', 'description' => 'Configure daisyUI 5 themes and the Lazy UI theme switcher.'],
        'livewire' => ['title' => 'Livewire', 'description' => 'Use Lazy UI with Livewire 4, wire:model and file uploads.'],
    ],
    'categories' => [
        "Actions" => [
            'button' => ['name' => 'Button', 'tag' => 'btn', 'description' => 'Primary action buttons, links, sizes, states and semantic variants.', 'example' => '<x-lazy-btn primary>Save</x-lazy-btn>'],
            'dropdown' => ['name' => 'Dropdown', 'tag' => 'dropdown', 'description' => 'Dropdown trigger and content with daisyUI 5 alignment helpers.', 'example' => '<x-lazy-dropdown end>Menu content</x-lazy-dropdown>'],
            'fab' => ['name' => 'FAB', 'tag' => 'fab', 'description' => 'Floating action button for primary page actions.', 'example' => '<x-lazy-fab>+</x-lazy-fab>'],
            'modal' => ['name' => 'Modal', 'tag' => 'modal', 'description' => 'Accessible modal dialog with Blade content.', 'example' => '<x-lazy-modal id="demo-modal">Modal content</x-lazy-modal>'],
            'swap' => ['name' => 'Swap', 'tag' => 'swap', 'description' => 'Swap two visual states, controlled or checkbox driven.', 'example' => '<x-lazy-swap><x-slot:on>ON</x-slot:on><x-slot:off>OFF</x-slot:off></x-lazy-swap>'],
            'theme-controller' => ['name' => 'Theme Controller', 'tag' => 'theme-controller', 'description' => 'Native daisyUI theme controller input.', 'example' => '<x-lazy-theme-controller value="dark" />'],
            'theme-switcher' => ['name' => 'Theme Switcher', 'tag' => 'theme-switcher', 'description' => 'Ready-made multi-theme or light/dark theme picker.', 'example' => '<x-lazy-theme-switcher />'],
        ],
        "Data display" => [
            'accordion' => ['name' => 'Accordion', 'tag' => 'accordion', 'description' => 'Grouped collapsible content.', 'example' => '<x-lazy-accordion title="Details">Content</x-lazy-accordion>'],
            'aura' => ['name' => 'Aura', 'tag' => 'aura', 'description' => 'Decorative aura container.', 'example' => '<x-lazy-aura>Content</x-lazy-aura>'],
            'avatar' => ['name' => 'Avatar', 'tag' => 'avatar', 'description' => 'Image avatar with online, offline and placeholder support.', 'example' => '<x-lazy-avatar class="w-12 rounded-full" src="/avatar.jpg" alt="User" />'],
            'avatar-group' => ['name' => 'Avatar Group', 'tag' => 'avatar-group', 'description' => 'Overlapping avatar collection.', 'example' => '<x-lazy-avatar-group><x-lazy-avatar class="w-10" src="/a.jpg" /></x-lazy-avatar-group>'],
            'badge' => ['name' => 'Badge', 'tag' => 'badge', 'description' => 'Status and metadata badge.', 'example' => '<x-lazy-badge success label="Ready" />'],
            'card' => ['name' => 'Card', 'tag' => 'card', 'description' => 'Content card with optional link and hover state.', 'example' => '<x-lazy-card title="Project">Card body</x-lazy-card>'],
            'carousel' => ['name' => 'Carousel', 'tag' => 'carousel', 'description' => 'Scrollable carousel container and items.', 'example' => '<x-lazy-carousel><x-lazy-carousel-item>Slide 1</x-lazy-carousel-item></x-lazy-carousel>'],
            'chat' => ['name' => 'Chat', 'tag' => 'chat', 'description' => 'Chat bubble layout.', 'example' => '<x-lazy-chat end message="Hello" />'],
            'collapse' => ['name' => 'Collapse', 'tag' => 'collapse', 'description' => 'Collapsible panel with controlled summary.', 'example' => '<x-lazy-collapse><x-slot:summary>Open</x-slot:summary>Content</x-lazy-collapse>'],
            'countdown' => ['name' => 'Countdown', 'tag' => 'countdown', 'description' => 'Numeric countdown display.', 'example' => '<x-lazy-countdown :value="42" />'],
            'diff' => ['name' => 'Diff', 'tag' => 'diff', 'description' => 'Before/after visual comparison.', 'example' => '<x-lazy-diff>...</x-lazy-diff>'],
            'hover-3d' => ['name' => 'Hover 3D', 'tag' => 'hover-3d', 'description' => 'Interactive 3D hover presentation.', 'example' => '<x-lazy-hover-3d>Card</x-lazy-hover-3d>'],
            'hover-gallery' => ['name' => 'Hover Gallery', 'tag' => 'hover-gallery', 'description' => 'Hover-driven image gallery.', 'example' => '<x-lazy-hover-gallery>...</x-lazy-hover-gallery>'],
            'image' => ['name' => 'Image', 'tag' => 'image', 'description' => 'Image wrapper with forwarded HTML attributes.', 'example' => '<x-lazy-image src="/image.jpg" alt="Example" />'],
            'kbd' => ['name' => 'Kbd', 'tag' => 'kbd', 'description' => 'Keyboard key label.', 'example' => '<x-lazy-kbd>⌘ K</x-lazy-kbd>'],
            'list' => ['name' => 'List', 'tag' => 'list', 'description' => 'Structured list with rows.', 'example' => '<x-lazy-list><x-lazy-list-row>Item</x-lazy-list-row></x-lazy-list>'],
            'stat' => ['name' => 'Stat', 'tag' => 'stat', 'description' => 'Single statistic block.', 'example' => '<x-lazy-stat title="Users" value="128" />'],
            'status' => ['name' => 'Status', 'tag' => 'status', 'description' => 'Small status indicator.', 'example' => '<x-lazy-status success />'],
            'table' => ['name' => 'Table', 'tag' => 'table', 'description' => 'Responsive daisyUI table wrapper.', 'example' => '<x-lazy-table>...</x-lazy-table>'],
            'text-rotate' => ['name' => 'Text Rotate', 'tag' => 'text-rotate', 'description' => 'Rotating text presentation.', 'example' => '<x-lazy-text-rotate :items="[\'Fast\',\'Simple\']" />'],
            'timeline' => ['name' => 'Timeline', 'tag' => 'timeline', 'description' => 'Timeline with timeline items.', 'example' => '<x-lazy-timeline><x-lazy-timeline-item>Release</x-lazy-timeline-item></x-lazy-timeline>'],
        ],
        "Navigation" => [
            'breadcrumbs' => ['name' => 'Breadcrumbs', 'tag' => 'breadcrumbs', 'description' => 'Breadcrumb navigation.', 'example' => '<x-lazy-breadcrumbs :items="[[\'label\' => \'Home\', \'href\' => \'/\'], [\'label\' => \'Docs\']]" />'],
            'dock' => ['name' => 'Dock', 'tag' => 'dock', 'description' => 'Bottom dock navigation.', 'example' => '<x-lazy-dock><x-lazy-dock-item label="Home" /></x-lazy-dock>'],
            'link' => ['name' => 'Link', 'tag' => 'link', 'description' => 'Semantic styled link.', 'example' => '<x-lazy-link primary href="/docs">Docs</x-lazy-link>'],
            'megamenu' => ['name' => 'Megamenu', 'tag' => 'megamenu', 'description' => 'Large navigation menu.', 'example' => '<x-lazy-megamenu>...</x-lazy-megamenu>'],
            'menu' => ['name' => 'Menu', 'tag' => 'menu', 'description' => 'daisyUI menu item wrapper.', 'example' => '<x-lazy-menu label="Dashboard" href="/admin" />'],
            'navbar' => ['name' => 'Navbar', 'tag' => 'navbar', 'description' => 'Navbar layout container.', 'example' => '<x-lazy-navbar>Navigation</x-lazy-navbar>'],
            'pagination' => ['name' => 'Pagination', 'tag' => 'pagination', 'description' => 'Pagination container and items.', 'example' => '<x-lazy-pagination>...</x-lazy-pagination>'],
            'steps' => ['name' => 'Steps', 'tag' => 'steps', 'description' => 'Process steps with individual step items.', 'example' => '<x-lazy-steps><x-lazy-step primary>Install</x-lazy-step></x-lazy-steps>'],
            'tabs' => ['name' => 'Tabs', 'tag' => 'tabs', 'description' => 'Tabs with daisyUI 5 styles.', 'example' => '<x-lazy-tabs><x-lazy-tab active>Preview</x-lazy-tab></x-lazy-tabs>'],
        ],
        "Feedback" => [
            'alert' => ['name' => 'Alert', 'tag' => 'alert', 'description' => 'Contextual alert message.', 'example' => '<x-lazy-alert success message="Saved" />'],
            'loading' => ['name' => 'Loading', 'tag' => 'loading', 'description' => 'Loading spinner variants.', 'example' => '<x-lazy-loading spinner lg />'],
            'progress' => ['name' => 'Progress', 'tag' => 'progress', 'description' => 'Linear progress indicator.', 'example' => '<x-lazy-progress primary :value="70" max="100" />'],
            'radial' => ['name' => 'Radial Progress', 'tag' => 'radial', 'description' => 'Circular progress indicator.', 'example' => '<x-lazy-radial :value="70">70%</x-lazy-radial>'],
            'skeleton' => ['name' => 'Skeleton', 'tag' => 'skeleton', 'description' => 'Loading placeholder.', 'example' => '<x-lazy-skeleton class="h-8 w-40" />'],
            'toast' => ['name' => 'Toast', 'tag' => 'toast', 'description' => 'Toast container used by Lazy UI notifications.', 'example' => '<x-lazy-toast />'],
            'tooltip' => ['name' => 'Tooltip', 'tag' => 'tooltip', 'description' => 'Tooltip around arbitrary content.', 'example' => '<x-lazy-tooltip tip="Help" top><button>?</button></x-lazy-tooltip>'],
            'error' => ['name' => 'Error', 'tag' => 'error', 'description' => 'Validation/error feedback.', 'example' => '<x-lazy-error message="Something went wrong" />'],
        ],
        "Inputs" => [
            'calendar' => ['name' => 'Calendar', 'tag' => 'calendar', 'description' => 'Calendar/date input component.', 'example' => '<x-lazy-calendar wire:model="date" />'],
            'checkbox' => ['name' => 'Checkbox', 'tag' => 'checkbox', 'description' => 'Checkbox input.', 'example' => '<x-lazy-checkbox name="terms" label="Accept" />'],
            'choices' => ['name' => 'Choices', 'tag' => 'choices', 'description' => 'Enhanced multi/single select choices.', 'example' => '<x-lazy-choices wire:model="tags" :options="$tags" />'],
            'fieldset' => ['name' => 'Fieldset', 'tag' => 'fieldset', 'description' => 'Fieldset and legend wrapper.', 'example' => '<x-lazy-fieldset legend="Profile">...</x-lazy-fieldset>'],
            'file-input' => ['name' => 'File Input', 'tag' => 'file-input', 'description' => 'File upload input.', 'example' => '<x-lazy-file-input name="avatar" />'],
            'filter' => ['name' => 'Filter', 'tag' => 'filter', 'description' => 'Filter chips/control.', 'example' => '<x-lazy-filter>...</x-lazy-filter>'],
            'input' => ['name' => 'Text Input', 'tag' => 'input', 'description' => 'Text input with semantic daisyUI variants.', 'example' => '<x-lazy-input name="name" placeholder="Name" />'],
            'label' => ['name' => 'Label', 'tag' => 'label', 'description' => 'Form label helper.', 'example' => '<x-lazy-label for="email">Email</x-lazy-label>'],
            'otp' => ['name' => 'OTP', 'tag' => 'otp', 'description' => 'One-time-password input.', 'example' => '<x-lazy-otp wire:model="code" :length="6" />'],
            'radio' => ['name' => 'Radio', 'tag' => 'radio', 'description' => 'Radio input.', 'example' => '<x-lazy-radio name="plan" value="pro" />'],
            'range' => ['name' => 'Range', 'tag' => 'range', 'description' => 'Range slider.', 'example' => '<x-lazy-range primary min="0" max="100" value="50" />'],
            'rating' => ['name' => 'Rating', 'tag' => 'rating', 'description' => 'Rating input.', 'example' => '<x-lazy-rating name="rating" />'],
            'richtext' => ['name' => 'Rich Text', 'tag' => 'richtext', 'description' => 'Quill 2 rich text editor.', 'example' => '<x-lazy-richtext wire:model="body" />'],
            'select' => ['name' => 'Select', 'tag' => 'select', 'description' => 'Select input.', 'example' => '<x-lazy-select name="country" :options="$countries" />'],
            'textarea' => ['name' => 'Textarea', 'tag' => 'textarea', 'description' => 'Multiline input.', 'example' => '<x-lazy-textarea name="bio" rows="4" />'],
            'toggle' => ['name' => 'Toggle', 'tag' => 'toggle', 'description' => 'Toggle switch.', 'example' => '<x-lazy-toggle name="enabled" />'],
        ],
        "Forms" => [
            'form' => ['name' => 'Form', 'tag' => 'form', 'description' => 'Form wrapper for standard or Livewire submit flows.', 'example' => '<x-lazy-form wire:submit="save">...</x-lazy-form>'],
            'form-group' => ['name' => 'Form Group', 'tag' => 'form-group', 'description' => 'Label, control and validation grouping.', 'example' => '<x-lazy-form-group label="Email">...</x-lazy-form-group>'],
            'form-input' => ['name' => 'Form Input', 'tag' => 'form-input', 'description' => 'Opinionated labeled text input.', 'example' => '<x-lazy-form-input wire:model="name" label="Name" />'],
            'form-select' => ['name' => 'Form Select', 'tag' => 'form-select', 'description' => 'Opinionated labeled select.', 'example' => '<x-lazy-form-select wire:model="role" label="Role" :options="$roles" />'],
            'form-textarea' => ['name' => 'Form Textarea', 'tag' => 'form-textarea', 'description' => 'Opinionated labeled textarea.', 'example' => '<x-lazy-form-textarea wire:model="bio" label="Bio" />'],
            'form-checkbox' => ['name' => 'Form Checkbox', 'tag' => 'form-checkbox', 'description' => 'Opinionated labeled checkbox.', 'example' => '<x-lazy-form-checkbox wire:model="active" label="Active" />'],
            'form-toggle' => ['name' => 'Form Toggle', 'tag' => 'form-toggle', 'description' => 'Opinionated labeled toggle.', 'example' => '<x-lazy-form-toggle wire:model="enabled" label="Enabled" />'],
            'form-image' => ['name' => 'Form Image', 'tag' => 'form-image', 'description' => 'Image/file input for Livewire uploads.', 'example' => '<x-lazy-form-image wire:model="photo" label="Photo" />'],
            'form-richtext' => ['name' => 'Form Rich Text', 'tag' => 'form-richtext', 'description' => 'Labeled Quill 2 editor.', 'example' => '<x-lazy-form-richtext wire:model="body" label="Body" />'],
        ],
        "Layout" => [
            'divider' => ['name' => 'Divider', 'tag' => 'divider', 'description' => 'Horizontal or vertical divider.', 'example' => '<x-lazy-divider>OR</x-lazy-divider>'],
            'drawer' => ['name' => 'Drawer', 'tag' => 'drawer', 'description' => 'Responsive drawer layout.', 'example' => '<x-lazy-drawer>...</x-lazy-drawer>'],
            'footer' => ['name' => 'Footer', 'tag' => 'footer', 'description' => 'Footer layout helper.', 'example' => '<x-lazy-footer>Footer content</x-lazy-footer>'],
            'hero' => ['name' => 'Hero', 'tag' => 'hero', 'description' => 'Hero layout section.', 'example' => '<x-lazy-hero>Hero content</x-lazy-hero>'],
            'indicator' => ['name' => 'Indicator', 'tag' => 'indicator', 'description' => 'Overlay indicator/badge positioning.', 'example' => '<x-lazy-indicator>...</x-lazy-indicator>'],
            'join' => ['name' => 'Join', 'tag' => 'join', 'description' => 'Join multiple controls into one visual group.', 'example' => '<x-lazy-join><x-lazy-btn>One</x-lazy-btn><x-lazy-btn>Two</x-lazy-btn></x-lazy-join>'],
            'mask' => ['name' => 'Mask', 'tag' => 'mask', 'description' => 'Image/content masks including compatibility masks.', 'example' => '<x-lazy-mask squircle><img src="/image.jpg" alt="" /></x-lazy-mask>'],
            'stack' => ['name' => 'Stack', 'tag' => 'stack', 'description' => 'Stacked visual layers.', 'example' => '<x-lazy-stack>...</x-lazy-stack>'],
        ],
        "Mockup" => [
            'mockup-browser' => ['name' => 'Browser Mockup', 'tag' => 'mockup-browser', 'description' => 'Browser frame mockup.', 'example' => '<x-lazy-mockup-browser>https://example.com</x-lazy-mockup-browser>'],
            'mockup-code' => ['name' => 'Code Mockup', 'tag' => 'mockup-code', 'description' => 'Terminal/code mockup.', 'example' => '<x-lazy-mockup-code>npm install</x-lazy-mockup-code>'],
            'mockup-phone' => ['name' => 'Phone Mockup', 'tag' => 'mockup-phone', 'description' => 'Phone frame mockup.', 'example' => '<x-lazy-mockup-phone>...</x-lazy-mockup-phone>'],
            'mockup-window' => ['name' => 'Window Mockup', 'tag' => 'mockup-window', 'description' => 'Desktop window mockup.', 'example' => '<x-lazy-mockup-window>...</x-lazy-mockup-window>'],
        ],
    ],
];
